services:

  api:
    build: .
    container_name: api-gestao
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      API_SECURITY_TOKEN_SECRET: ${JWT_SECRET}

  postgres:
    image: postgres:16
    container_name: postgres-gestao
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: