ALTER TABLE proprietario ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE atendimento ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE despesa ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE servico ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
